inputs_arguments:
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/framework.py
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/ops/inventory_op.py
- issue
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/exception.py
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/metrics/metric_entity.py
- failure
- KB 6691
- /home/nutanix/cluster/lib/storcli/storcli64
- error
- /home/nutanix/data/logs/genesis.out
- exception
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/ops/distribute_op_tasks.py
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/base_classes/base_op.py
- /home/nutanix/data/logs/lcm_ops.out
- KB 1294
- /01/25
- /usr/bin/sudo
- /c0
inputs_count: 18
knowledge_base:
  extraction_date: '2025-01-28'
  source_file: /home/rangu.ushasri/src/main/views/hack1/NLP-Based-KBA-Hackathon-/data/raw/KB-1.pdf
