categorized_inputs:
  error:
  - failure
  - exception
  - error
  - issue
  file_path:
  - /usr/bin/sudo
  - /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/ops/inventory_op.py
  - /c0
  - /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/metrics/metric_entity.py
  - /home/nutanix/data/logs/genesis.out
  - /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/base_classes/base_op.py
  - /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/framework.py
  - /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/ops/distribute_op_tasks.py
  - /home/nutanix/data/logs/lcm_ops.out
  - /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/exception.py
  - /home/nutanix/cluster/lib/storcli/storcli64
  ip_address: []
  maintenance_term: []
  precheck: []
inputs_arguments:
- /usr/bin/sudo
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/ops/inventory_op.py
- exception
- /c0
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/metrics/metric_entity.py
- /home/nutanix/data/logs/genesis.out
- failure
- issue
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/framework.py
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/base_classes/base_op.py
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/ops/distribute_op_tasks.py
- /home/nutanix/data/logs/lcm_ops.out
- /tmp/lcm_framework_tmp_tin8rfiz/bdist.linux-x86_64/egg/framework/main/exception.py
- error
- /home/nutanix/cluster/lib/storcli/storcli64
inputs_count: 15
knowledge_base:
  extraction_date: '2025-01-28'
  source_file: /home/rangu.ushasri/src/main/views/hack1/NLP-Based-KBA-Hackathon-/data/raw/KB-1.pdf
