actions:
- action: resolve
  context: Resolving an issue where LCM Inventory task fails with error " ' NoneType'object
    is not subscriptable"
- action: affect
  context: "Versions affected : LCM 3.1 \n LCMDescription : LCM Inventory task fails\
    \ with the error message : Veri\uFB01cation:1 . SSH to the LCM leader.2 ."
- action: state
  context: in /home / nutanix / data / logs / lcm_ops.out on theCVM stated in the
    inventory failure message
- action: fail
  context: If the task fails again
- action: engage
  context: If the task fails again , engage Nutanix Support for assistancein troubleshooting
    .
- action: collect
  context: Collecting additional informationCollect
- action: use
  context: using the following command on the CVM
- action: attach
  context: as user nutanixand attach it to the case
- action: follow
  context: ( follow KB 1294
- action: see
  context: "For more information on Logbay , see \_ KB 6691.If"
- action: exceed
  context: "the size of the \uFB01les being uploaded exceeds 5 GB , use the Nutanix\
    \ FTP server due tosupported size limitations ."
- action: fail
  context: 'The Command : [ '' /usr / bin / sudo '' , '' /home / nutanix / cluster
    / lib / storcli / storcli64 '' , '' /c0 '' , '' show '' , '' all '' , '' J ''
    ] failed at Attempt : 1 with Output : , Error : '' utf-8 '' codec ca n''t decode
    byte 0xdf in position 9750 : invalid continuation byte , Return Code : -12025
    - 01 - 16 12:47:31,901Z INFO 59871616 helper.py:148 DEBUG :'
- action: show
  context: "Failure in running the cmd : /home / nutanix / cluster / lib / storcli\
    \ / storcli64 /c0 show all J2025 - 01 - 16 12:47:31,901Z INFO 59871616 helper.py:148\
    \ ret : -1 , \n logbay collect --aggregate = true \n 25/01/25 , 9:40 \u202F AM\
    \ \n Page 4 of 4about : srcdocIf traces and errors match , collect logs and attach\
    \ the case to ENG-733929 . \_"
- action: decodethe
  context: to decodethe hardware
- action: show
  context: "nutanix@NTNX - CVM:~$ /usr / bin / sudo /home / nutanix / cluster / lib\
    \ / storcli / storcli64 /c0 show all J \n"
dependencies:
  ? '

    '
  : dependency: dep
    head: J
  '#':
    dependency: compound
    head: "modi\uFB01ed"
  '''':
    dependency: dep
    head: is
  '-':
    dependency: appos
    head: Solution
  '-12025':
    dependency: appos
    head: Code
  /c0:
    dependency: dobj
    head: storcli64
  /home:
    dependency: nmod
    head: lcm_ops.out
  /tmp:
    dependency: nmod
    head: bdist.linux
  '01':
    dependency: nummod
    head: J2025
  '06:47:31.569505':
    dependency: nmod
    head: Number
  '0xdf':
    dependency: dobj
    head: decode
  '1':
    dependency: prep
    head: failed
  '1075':
    dependency: nummod
    head: line
  '12025':
    dependency: nummod
    head: helper.py:148
  '1294':
    dependency: nummod
    head: KB
  12:47:31,901Z:
    dependency: nummod
    head: J2025
  12:49:55,587Z:
    dependency: prep
    head: '01'
  '15':
    dependency: nummod
    head: 12:49:55,587Z
  '16':
    dependency: prep
    head: J2025
  '2':
    dependency: nummod
    head: Page
  '2025':
    dependency: nummod
    head: '06:47:31.805413'
  2025VisibilityCustomersSummary:
    dependency: acomp
    head: is
  '2124':
    dependency: npadvmod
    head: line
  '235':
    dependency: nummod
    head: line
  '2375':
    dependency: nummod
    head: line
  '2470':
    dependency: nummod
    head: line
  24th:
    dependency: npadvmod
    head: is
  25/01/25:
    dependency: nmod
    head: traces
  '285':
    dependency: nummod
    head: line
  '297':
    dependency: nummod
    head: line
  '3':
    dependency: nummod
    head: Page
  '3.1':
    dependency: nummod
    head: LCM
  '347':
    dependency: nummod
    head: line
  '4':
    dependency: nummod
    head: Page
  '410':
    dependency: nummod
    head: line
  4about:
    dependency: pobj
    head: of
  '5':
    dependency: nummod
    head: GB
  '51339968':
    dependency: nummod
    head: ERROR
  '59871616':
    dependency: nummod
    head: INFO
  6691.If:
    dependency: dobj
    head: see
  '9750':
    dependency: nummod
    head: position
  '9:40':
    dependency: nummod
    head: AM
  '=':
    dependency: nsubj
    head: match
  AM:
    dependency: compound
    head: Page
  Attempt:
    dependency: pobj
    head: at
  CVM:
    dependency: pobj
    head: 'On'
  CVM:~$:
    dependency: nsubj
    head: storcli64
  Code:
    dependency: appos
    head: byte
  Collecting:
    dependency: advcl
    head: bundle
  Command:
    dependency: nsubj
    head: failed
  DEBUG:
    dependency: conj
    head: failed
  ENG-733929:
    dependency: pobj
    head: to
  ERROR:
    dependency: nmod
    head: 25/01/25
  Error:
    dependency: nmod
    head: codec
  FTP:
    dependency: nmod
    head: server
  Failed:
    dependency: npadvmod
    head: found
  Failure:
    dependency: nsubj
    head: show
  For:
    dependency: prep
    head: see
  GB:
    dependency: dobj
    head: exceeds
  HBAs:
    dependency: pobj
    head: of
  INFO:
    dependency: nmod
    head: ret
  If:
    dependency: mark
    head: fails
  Internal:
    dependency: amod
    head: Comments
  Inventory:
    dependency: compound
    head: task
  J:
    dependency: dobj
    head: show
  J2025:
    dependency: nmod
    head: ret
  KB:
    dependency: compound
    head: 6691.If
  KB-18275Last:
    dependency: compound
    head: "modi\uFB01ed"
  LCM:
    dependency: compound
    head: 25/01/25
  LCMDescription:
    dependency: nmod
    head: task
  LCMleader:
    dependency: pobj
    head: 'on'
  LcmExceptionHandler:
    dependency: dep
    head: found
  Logbay:
    dependency: pobj
    head: 'on'
  NoneType:
    dependency: nmod
    head: object
  NoneType'object:
    dependency: nsubj
    head: is
  Number:
    dependency: nsubj
    head: DEBUG
  Nutanix:
    dependency: compound
    head: FTP
  'On':
    dependency: prep
    head: stated
  Output:
    dependency: pobj
    head: with
  Page:
    dependency: appos
    head: 25/01/25
  Re:
    dependency: appos
    head: Solution
  Resolving:
    dependency: advcl
    head: is
  Return:
    dependency: compound
    head: Code
  SSH:
    dependency: appos
    head: message
  Support:
    dependency: dobj
    head: engage
  The:
    dependency: det
    head: Command
  "Veri\uFB01cation:1":
    dependency: appos
    head: message
  Versions:
    dependency: nsubj
    head: affected
  '[':
    dependency: dep
    head: '06:47:31.805413'
  _:
    dependency: pobj
    head: in
  able:
    dependency: acomp
    head: is
  additional:
    dependency: amod
    head: informationCollect
  again:
    dependency: advmod
    head: fails
  all:
    dependency: det
    head: J
  an:
    dependency: det
    head: error
  and:
    dependency: cc
    head: collect
  any:
    dependency: det
    head: characters
  as:
    dependency: mark
    head: attach
  assistancein:
    dependency: advmod
    head: troubleshooting
  at:
    dependency: prep
    head: failed
  attach:
    dependency: conj
    head: collect
  attempt:
    dependency: acl
    head: Solution
  base_classes:
    dependency: nmod
    head: base_op.py
  base_op.py:
    dependency: nmod
    head: detect_inventoryFile
  bdist.linux:
    dependency: appos
    head: distributed_inventoryFile
  being:
    dependency: auxpass
    head: uploaded
  below:
    dependency: advmod
    head: traceback
  bin:
    dependency: nmod
    head: sudo
  byte:
    dependency: dobj
    head: decode
  ca:
    dependency: aux
    head: decode
  call:
    dependency: nsubj
    head: last):File
  call__File:
    dependency: pobj
    head: in
  case:
    dependency: dobj
    head: attach
  characters:
    dependency: pobj
    head: to
  cluster:
    dependency: nmod
    head: lib
  cmd:
    dependency: dobj
    head: running
  codec:
    dependency: nsubj
    head: decode
  collect:
    dependency: conj
    head: collect
  command:
    dependency: dobj
    head: using
  continuation:
    dependency: compound
    head: byte
  "con\uFB01rm":
    dependency: compound
    head: storcli
  cvm:
    dependency: appos
    head: environment
  data:
    dependency: nmod
    head: logs
  decode:
    dependency: ccomp
    head: failed
  decodethe:
    dependency: xcomp
    head: able
  decoding:
    dependency: amod
    head: error
  distributed_inventoryFile:
    dependency: pobj
    head: in
  due:
    dependency: amod
    head: limitations
  during:
    dependency: prep
    head: related
  egg:
    dependency: nmod
    head: framework
  environment:
    dependency: appos
    head: x.x.x.25
  error:
    dependency: pobj
    head: in
  errors:
    dependency: conj
    head: traces
  exception.py:
    dependency: pobj
    head: last):File
  exception.py:86:
    dependency: compound
    head: 25/01/25
  failed:
    dependency: pcomp
    head: with
  failing:
    dependency: acl
    head: inventory
  fails:
    dependency: advcl
    head: engage
  failure:
    dependency: compound
    head: message
  follow:
    dependency: advcl
    head: bundle
  following:
    dependency: amod
    head: command
  for:
    dependency: prep
    head: engage
  found:
    dependency: ccomp
    head: failed
  framework:
    dependency: nmod
    head: main
  framework.py:
    dependency: pobj
    head: in
  genesis.out:
    dependency: pobj
    head: in
  hardware:
    dependency: dobj
    head: decodethe
  helper.py:148:
    dependency: compound
    head: ret
  in:
    dependency: prep
    head: stated
  information:
    dependency: pobj
    head: For
  informationCollect:
    dependency: dobj
    head: Collecting
  invalid:
    dependency: amod
    head: byte
  inventory:
    dependency: compound
    head: failure
  inventory_op.py:
    dependency: appos
    head: detect_inventoryFile
  is:
    dependency: auxpass
    head: related
  issue:
    dependency: nsubjpass
    head: related
  it:
    dependency: dobj
    head: attach
  last):File:
    dependency: parataxis
    head: subscriptable]]Traceback
  lcm_framework_tmp_tin8rfiz:
    dependency: nmod
    head: bdist.linux
  lcm_leaderLcm:
    dependency: compound
    head: leader
  lcm_ops.out:
    dependency: nsubj
    head: stated
  leader:
    dependency: nsubj
    head: is
  leader.2:
    dependency: pobj
    head: to
  lib:
    dependency: nmod
    head: storcli
  limitations:
    dependency: dobj
    head: use
  line:
    dependency: appos
    head: detect_inventoryFile
  logbay:
    dependency: nsubj
    head: collect
  logs:
    dependency: dobj
    head: collect
  main:
    dependency: amod
    head: ops
  match:
    dependency: ccomp
    head: collect
  message:
    dependency: compound
    head: storcli
  metric_entity.py:
    dependency: pobj
    head: in
  metrics:
    dependency: nmod
    head: metric_entity.py
  "modi\uFB01ed":
    dependency: attr
    head: is
  monitor_tasks_and_report_errorsframework.main.exception:
    dependency: pobj
    head: in
  more:
    dependency: amod
    head: information
  most:
    dependency: advmod
    head: recent
  n't:
    dependency: neg
    head: decode
  not:
    dependency: neg
    head: is
  notsubscriptableArticle:
    dependency: compound
    head: "modi\uFB01ed"
  nutanix:
    dependency: nmod
    head: storcli
  nutanix@NTNX:
    dependency: compound
    head: CVM:~$
  nutanixand:
    dependency: nsubj
    head: attach
  object:
    dependency: nsubj
    head: is
  of:
    dependency: prep
    head: Page
  'on':
    dependency: prep
    head: characters
  onJan:
    dependency: compound
    head: 24th
  ops:
    dependency: pobj
    head: in
  position:
    dependency: pobj
    head: in
  present:
    dependency: acomp
    head: is
  recent:
    dependency: amod
    head: call
  related:
    dependency: acl
    head: Comments
  release.smc.sas_update.update:
    dependency: pobj
    head: for
  repo:
    dependency: pobj
    head: during
  results:
    dependency: relcl
    head: repo
  ret:
    dependency: dobj
    head: show
  runFile:
    dependency: appos
    head: base_op.py
  run_operationsFile:
    dependency: pobj
    head: in
  running:
    dependency: pcomp
    head: in
  server:
    dependency: nmod
    head: limitations
  show:
    dependency: appos
    head: Command
  size:
    dependency: compound
    head: limitations
  srcdoc3:
    dependency: appos
    head: 25/01/25
  srcdocException:
    dependency: appos
    head: 25/01/25
  srcdocIf:
    dependency: compound
    head: traces
  srcdocLCM:
    dependency: compound
    head: inventory
  stated:
    dependency: csubj
    head: is
  storcli:
    dependency: nmod
    head: storcli64
  storcli64:
    dependency: nsubj
    head: show
  subscriptable:
    dependency: acomp
    head: is
  subscriptable":
    dependency: acomp
    head: is
  subscriptable]]Traceback:
    dependency: attr
    head: is
  sudo:
    dependency: nmod
    head: storcli64
  task:
    dependency: nsubj
    head: fails
  the:
    dependency: det
    head: storcli
  theCVM:
    dependency: pobj
    head: 'on'
  theInventory:
    dependency: compound
    head: repo
  to:
    dependency: aux
    head: decodethe
  tosupported:
    dependency: amod
    head: limitations
  traceback:
    dependency: nsubj
    head: is
  traces:
    dependency: nsubj
    head: match
  troubleshooting:
    dependency: pobj
    head: for
  'true':
    dependency: amod
    head: 25/01/25
  unconvertible:
    dependency: amod
    head: characters
  uploaded:
    dependency: acl
    head: size
  use:
    dependency: conj
    head: exceeds
  user:
    dependency: compound
    head: nutanixand
  using:
    dependency: advcl
    head: bundle
  utf-8:
    dependency: appos
    head: Error
  where:
    dependency: advmod
    head: fails
  which:
    dependency: nsubj
    head: results
  with:
    dependency: prep
    head: '1'
  wrapperFile:
    dependency: pobj
    head: in
  x.x.x.182:
    dependency: pobj
    head: 'on'
  x.x.x.25:
    dependency: pobj
    head: 'on'
  x.x.x.272025:
    dependency: compound
    head: 25/01/25
  x86_64:
    dependency: dobj
    head: distributed_inventoryFile
  "\_":
    dependency: dep
    head: .
  "\u202F":
    dependency: dep
    head: '9:40'
  "\uFB01les":
    dependency: pobj
    head: of
knowledge_base:
  extraction_date: '2025-01-27'
  source_file: KB-1.pdf
system_info:
  organizations:
  - LCM Inventory
  - LCM Inventory
  - SSH
  - NoneType
  - LCM
  - NoneType
  - NoneType
  - Inventory
  - CVM
  - Nutanix
  - FTP
  - theInventory
  - Attempt
  - '-1'
  - ENG-733929
  - CVM
  - nutanix@NTNX-CVM:~$ /usr/bin
  products:
  - LCMleader
  - Logbay
  - logbay
validations: []
