actions:
- action: '-'
  context: '- check test_hosts_in_maintenance_mode checks if any host is inMaintenance
    mode'
- action: affect
  context: "Versions affected : LCM 2.x \n LCMDescription : LCM pre - check test_hosts_in_maintenance_mode\
    \ checks if any host is in Maintenancemode ."
- action: '-'
  context: '-'
- action: leave
  context: "A \_ host could be left in maintenance due to previous upgrade failure\
    \ , maintenanceactivity etc . LCM update operation fails with the following error\
    \ when it detects 1 or more host(s ) inMaintenance mode . \n"
- action: detect
  context: when it detects 1 or more host(s ) inMaintenance mode
- action: identify
  context: "Identify the host that is not \_ Schedulable ."
- action: fail
  context: Operation failed .
- action: detect
  context: Lcm prechecks detected 1 issue that would cause upgrade failures .
- action: refer
  context: "Please refer to KB 9046 \n 25/01/25 , 9:39 \u202F AM \n Page 3 of 5about\
    \ : srcdoc2 ."
- action: check
  context: Check the status of the host:3 .
- action: check
  context: Check for Node_state -- > " kEnteredMaintenanceMode"4 .
- action: login
  context: Login to vCenter and check if any ESXi host is in Maintenance mode.2 .
- action: wait
  context: Wait for few mins until CVM is online and services are up.3 .
- action: check
  context: 'Check the status of cluster nodes : nutanix@CVM~$ acli host.get xx.xx.xx.11xx.xx.xx.xx
    {   cpu_usage_ppm :'
- action: cvm_memory_size_byte
  context: 'Check the status of cluster nodes : nutanix@CVM~$ acli host.get xx.xx.xx.11xx.xx.xx.xx
    {   cpu_usage_ppm : 35708   cvm_memory_size_bytes : 34359738368   cvm_num_vcpus
    : 12   cvm_uuid : " d39c8813 - 9029 - 4228 - ad5e - d1e82fc82e0f "   logical_timestamp
    :'
- action: mem_assigned_byte
  context: '201   max_mem_ha_reserved_bytes : 0   mem_assigned_bytes : 0   mem_usage_bytes
    : 38467761771   memory_size_bytes : 269889830912   node_state : " kEnteredMaintenanceMode
    "   num_cpus :'
- action: bring
  context: Bring it back online:3 .
dependencies:
  ? '

    '
  : dependency: dep
    head: HPVHST12
  ? "\n\_\n"
  : dependency: dep
    head: srcdoc
  ' ':
    dependency: dep
    head: 'False'
  '   ':
    dependency: dep
    head: '10'
  '    ':
    dependency: dep
    head: '5'
  '       ':
    dependency: dep
    head: 'False'
  '        ':
    dependency: dep
    head: 'True'
  '         ':
    dependency: dep
    head: HPVHST22
  '            ':
    dependency: dep
    head: kKvm
  '                ':
    dependency: dep
    head: '----'
  '                            ':
    dependency: dep
    head: UUID
  ? '                                                                                                                                      '
  : dependency: dep
    head: Paused
  ? '                                                                                                                                       '
  : dependency: dep
    head: '-----'
  ? '                                                                                                                                          '
  : dependency: dep
    head: Up
  '-':
    dependency: amod
    head: LCM
  '----':
    dependency: dobj
    head: update
  '-----':
    dependency: compound
    head: '1'
  .:
    dependency: compound
    head: operation
  '0':
    dependency: nummod
    head: mem_usage_bytes
  '1':
    dependency: nummod
    head: FalseIf
  '10':
    dependency: appos
    head: '1'
  '11':
    dependency: appos
    head: '1'
  '12':
    dependency: nummod
    head: cvm_uuid
  1b2c-4c79:
    dependency: prep
    head: '70167025'
  1e676a61cc54:
    dependency: prep
    head: 9cc4
  '2':
    dependency: appos
    head: '1'
  2.x:
    dependency: compound
    head: LCMDescription
  '201':
    dependency: nummod
    head: max_mem_ha_reserved_bytes
  2023Summary:
    dependency: nummod
    head: 25/01/25
  22nd:
    dependency: appos
    head: 25/01/25
  25/01/25:
    dependency: appos
    head: Name
  '269889830912':
    dependency: nummod
    head: node_state
  '3':
    dependency: appos
    head: '1'
  '34359738368':
    dependency: nummod
    head: cvm_num_vcpus
  '35708':
    dependency: nummod
    head: cvm_memory_size_bytes
  '38467761771':
    dependency: nsubj
    head: memory_size_bytes
  '4':
    dependency: appos
    head: '1'
  '4228':
    dependency: nummod
    head: d1e82fc82e0f
  '4363':
    dependency: appos
    head: output
  444d-872d:
    dependency: nummod
    head: d144a0c54c8e
  '5':
    dependency: nummod
    head: Upnutanix@NTNX
  56f1:
    dependency: nummod
    head: d144a0c54c8e
  58dffc17:
    dependency: nmod
    head: host.exit_maintenance_mode
  5about:
    dependency: pobj
    head: of
  '6':
    dependency: appos
    head: '1'
  65fa3fb3:
    dependency: appos
    head: kKvm
  67320f01:
    dependency: conj
    head: kKvm
  '7':
    dependency: appos
    head: '1'
  '70167025':
    dependency: nummod
    head: 'True'
  '8':
    dependency: appos
    head: '1'
  '80':
    dependency: nummod
    head: uuid
  85dc547ea9e4:
    dependency: prep
    head: '70167025'
  896e-48ff-87a6:
    dependency: prep
    head: 58dffc17
  '9':
    dependency: appos
    head: '1'
  '9029':
    dependency: nummod
    head: '4228'
  '9046':
    dependency: nummod
    head: KB
  '9:39':
    dependency: nummod
    head: Page
  '>':
    dependency: nmod
    head: FalseIf
  A:
    dependency: det
    head: host
  AHV1:
    dependency: pobj
    head: For
  AHVnutanix@CVM~$:
    dependency: compound
    head: acli
  AHVxx.xx.xx.xx:
    dependency: appos
    head: kKvm
  AM:
    dependency: compound
    head: Page
  B:
    dependency: compound
    head: CVM:10.xx.xx.xx:~$
  CVM:
    dependency: nsubj
    head: is
  CVM:10.xx.xx.xx:~$:
    dependency: npadvmod
    head: Upnutanix@NTNX
  Check:
    dependency: advcl
    head: cvm_memory_size_bytes
  Clusternode:
    dependency: pobj
    head: Up
  ClusternodeName:
    dependency: compound
    head: '----'
  Compute:
    dependency: appos
    head: acli
  DNS:
    dependency: compound
    head: Name
  ESXi:
    dependency: compound
    head: host
  ESXi1:
    dependency: pobj
    head: For
  Example:
    dependency: compound
    head: output
  Exit:
    dependency: compound
    head: mode
  'False':
    dependency: amod
    head: uuid
  FalseIf:
    dependency: appos
    head: value
  For:
    dependency: prep
    head: 25/01/25
  Get:
    dependency: compound
    head: ClusternodeName
  HPVHST12:
    dependency: dep
    head: '1'
  HPVHST13:
    dependency: compound
    head: '7'
  HPVHST14:
    dependency: dep
    head: '1'
  HPVHST15:
    dependency: dep
    head: '1'
  HPVHST16:
    dependency: npadvmod
    head: '1'
  HPVHST17:
    dependency: dep
    head: '1'
  HPVHST18:
    dependency: dep
    head: '1'
  HPVHST19:
    dependency: dep
    head: '1'
  HPVHST20:
    dependency: appos
    head: '1'
  HPVHST21:
    dependency: dep
    head: '1'
  Host:
    dependency: compound
    head: UUID
  Hosts:
    dependency: nsubj
    head: are
  Hyper:
    dependency: compound
    head: V1
  Hypervisor:
    dependency: conj
    head: IP
  ID:
    dependency: compound
    head: State
  IP:
    dependency: nmod
    head: Name
  If:
    dependency: mark
    head: is
  In:
    dependency: prep
    head: is
  KB:
    dependency: pobj
    head: to
  KB-9046Last:
    dependency: compound
    head: "modi\uFB01ed"
  LCM:
    dependency: nsubj
    head: update
  LCMDescription:
    dependency: appos
    head: LCM
  Lcm:
    dependency: compound
    head: prechecks
  Maintenance:
    dependency: compound
    head: mode
  Maintenancemode:
    dependency: pobj
    head: in
  Mode:
    dependency: pobj
    head: in
  Name:
    dependency: appos
    head: uuid
  Namexx.xx.xx.11:
    dependency: compound
    head: xx.xx.xx.xx
  Node_state:
    dependency: pobj
    head: for
  Nutanix:
    dependency: compound
    head: Support
  Only:
    dependency: advmod
    head: Schedulable
  Operation:
    dependency: nsubj
    head: failed
  Otherwise:
    dependency: advmod
    head: Support
  Page:
    dependency: appos
    head: 25/01/25
  Paused:
    dependency: compound
    head: HPVHST13
  Please:
    dependency: intj
    head: refer
  Pre:
    dependency: appos
    head: Page
  Re:
    dependency: meta
    head: update
  Resume:
    dependency: compound
    head: Clusternode
  Schedulable:
    dependency: compound
    head: xx.xx.xx.xx
  Solution:
    dependency: appos
    head: Page
  State:
    dependency: compound
    head: '----'
  'True':
    dependency: compound
    head: kKvm
  Type:
    dependency: compound
    head: Hypervisor
  UUID:
    dependency: conj
    head: Name
  Up:
    dependency: advmod
    head: '1'
  Upnutanix@NTNX:
    dependency: nmod
    head: Clusternode
  V1:
    dependency: dobj
    head: update
  Versions:
    dependency: nsubj
    head: affected
  XXX:
    dependency: nmod
    head: B
  a:
    dependency: det
    head: state
  ac04:
    dependency: prep
    head: 1b2c-4c79
  acli:
    dependency: amod
    head: host.exit_maintenance_mode
  ad5e:
    dependency: nmod
    head: d1e82fc82e0f
  and:
    dependency: cc
    head: online
  any:
    dependency: det
    head: host
  are:
    dependency: conj
    head: Wait
  back:
    dependency: advmod
    head: Bring
  be:
    dependency: auxpass
    head: left
  cause:
    dependency: relcl
    head: issue
  check:
    dependency: conj
    head: Login
  checks:
    dependency: dobj
    head: affected
  cluster:
    dependency: compound
    head: nodes
  contact:
    dependency: compound
    head: Support
  could:
    dependency: aux
    head: left
  cpu_usage_ppm:
    dependency: appos
    head: acli
  cvm_num_vcpus:
    dependency: npadvmod
    head: cvm_memory_size_bytes
  cvm_uuid:
    dependency: appos
    head: cvm_num_vcpus
  d144a0c54c8e:
    dependency: nmod
    head: 'True'
  d1e82fc82e0f:
    dependency: nmod
    head: logical_timestamp
  d39c8813:
    dependency: nmod
    head: logical_timestamp
  detects:
    dependency: advcl
    head: fails
  due:
    dependency: prep
    head: left
  e90b23b20471:
    dependency: conj
    head: 58dffc17
  e90b23b20471"}nutanix@CVM~$:
    dependency: nummod
    head: 58dffc17
  error:
    dependency: pobj
    head: with
  etc:
    dependency: cc
    head: maintenanceactivity
  example:
    dependency: pobj
    head: In
  exit:
    dependency: compound
    head: maintenance
  failed:
    dependency: ccomp
    head: Check
  fails:
    dependency: conj
    head: left
  failure:
    dependency: pobj
    head: to
  failures:
    dependency: dobj
    head: cause
  few:
    dependency: amod
    head: mins
  following:
    dependency: amod
    head: error
  for:
    dependency: prep
    head: Wait
  host:
    dependency: nsubj
    head: is
  host(s:
    dependency: nmod
    head: mode
  host.6:
    dependency: pobj
    head: for
  host.exit_maintenance_mode:
    dependency: nmod
    head: Name
  host.get:
    dependency: appos
    head: acli
  host.listHypervisor:
    dependency: compound
    head: IP
  host:3:
    dependency: pobj
    head: of
  if:
    dependency: mark
    head: is
  in:
    dependency: prep
    head: is
  inMaintenance:
    dependency: compound
    head: mode
  is:
    dependency: advcl
    head: Wait
  issue:
    dependency: dobj
    head: detected
  it:
    dependency: dobj
    head: Bring
  kEnteredMaintenanceMode:
    dependency: nmod
    head: num_cpus
  kEnteredMaintenanceMode"4:
    dependency: dobj
    head: Check
  kKvm:
    dependency: appos
    head: output
  logical_timestamp:
    dependency: appos
    head: cvm_uuid
  maintenance:
    dependency: compound
    head: mode
  maintenanceactivity:
    dependency: appos
    head: failure
  max_mem_ha_reserved_bytes:
    dependency: dep
    head: mem_assigned_bytes
  mem_usage_bytes:
    dependency: appos
    head: mem_assigned_bytes
  memory_size_bytes:
    dependency: parataxis
    head: mem_usage_bytes
  mins:
    dependency: pobj
    head: for
  mode:
    dependency: appos
    head: Mode
  mode.2:
    dependency: pobj
    head: in
  "modi\uFB01ed":
    dependency: compound
    head: onNov
  more:
    dependency: conj
    head: '1'
  next:
    dependency: amod
    head: step
  node:
    dependency: nsubj
    head: is
  node_state:
    dependency: conj
    head: mem_usage_bytes
  nodes:
    dependency: pobj
    head: of
  not:
    dependency: neg
    head: is
  num_cpus:
    dependency: appos
    head: node_state
  nutanix@CVM~$:
    dependency: compound
    head: acli
  of:
    dependency: prep
    head: Page
  onNov:
    dependency: appos
    head: 25/01/25
  online:
    dependency: acomp
    head: is
  online:3:
    dependency: dobj
    head: Bring
  operation:
    dependency: conj
    head: maintenanceactivity
  operation.nutanix@NTNX:
    dependency: nmod
    head: winsh192.168.5.1
  operationFor:
    dependency: compound
    head: V1
  or:
    dependency: cc
    head: Name
  prechecks:
    dependency: nsubj
    head: detected
  previous:
    dependency: amod
    head: failure
  proceed:
    dependency: conj
    head: are
  run:
    dependency: amod
    head: LCM
  schedulable:
    dependency: amod
    head: '80'
  services:
    dependency: conj
    head: online
  srcdoc:
    dependency: amod
    head: Solution
  srcdoc2:
    dependency: appos
    head: Name
  srcdoc5:
    dependency: appos
    head: output
  srcdocLCM:
    dependency: nmod
    head: Pre
  state:
    dependency: pobj
    head: in
  status:
    dependency: dobj
    head: Check
  step:
    dependency: pobj
    head: to
  test_hosts_in_maintenance_mode:
    dependency: nsubj
    head: failed
  test_hosts_in_maintenance_modeArticle:
    dependency: compound
    head: KB-9046Last
  that:
    dependency: det
    head: host.6
  the:
    dependency: det
    head: node
  this:
    dependency: det
    head: example
  to:
    dependency: prep
    head: Login
  until:
    dependency: mark
    head: is
  up.3:
    dependency: attr
    head: are
  update:
    dependency: compound
    head: operation
  upgrade:
    dependency: compound
    head: failures
  vCenter:
    dependency: pobj
    head: to
  value:
    dependency: pobj
    head: for
  when:
    dependency: advmod
    head: detects
  winsh:
    dependency: amod
    head: Clusternode
  winsh192.168.5.1:
    dependency: nmod
    head: '----'
  with:
    dependency: prep
    head: fails
  would:
    dependency: aux
    head: cause
  xx.x.xx.10:
    dependency: appos
    head: Hosts
  xx.x.xx.11:
    dependency: appos
    head: Hosts
  xx.xx.xx.11xx.xx.xx.xx:
    dependency: appos
    head: host.get
  xx.xx.xx.xx:
    dependency: nummod
    head: kKvm
  "\_":
    dependency: dep
    head: Exit
  "\u202F":
    dependency: dep
    head: '9:39'
knowledge_base:
  extraction_date: '2025-01-27'
  source_file: KB-2.pdf
system_info:
  organizations:
  - Maintenancemode
  - LCM
  - IP
  - Hypervisor DNS Name
  - LCM
  - CVM
  - LCM
  - Hyper-V1
  - LCM
  - operation.nutanix@NTNX
  - Resume-Clusternode
  products:
  - host.exit_maintenance_mode
validations:
- "25/01/25, 9:39\u202FAM\nPage 1 of 5about:srcdocLCM Pre-check:test_hosts_in_maintenance_modeArticle\
  \ #KB-9046Last modi\uFB01ed onNov 22nd 2023Summary:LCM pre-check test_hosts_in_maintenance_mode\
  \ checks if any host is inMaintenance mode."
- 'Versions affected:LCM 2.x

  LCMDescription:LCM pre-check test_hosts_in_maintenance_mode checks if any host is
  in Maintenancemode.'
- Lcm prechecks detected 1 issue that would cause upgrade failures.
- 'Check ''test_hosts_in_maintenance_mode'' failed: Hosts xx.x.xx.10 xx.x.xx.11 are
  in maintenance mode.'
- Check the status of the host:3.
- Check for Node_state --> "kEnteredMaintenanceMode"4.
- "Check for \"Schedulable\" value --> FalseIf\_1 and 2 are True, proceed to the next\
  \ step."
- Login to vCenter and check if any ESXi host is in Maintenance mode.2.
- 'Check the status of cluster nodes:nutanix@CVM~$ acli host.get xx.xx.xx.11xx.xx.xx.xx
  {  cpu_usage_ppm: 35708  cvm_memory_size_bytes: 34359738368  cvm_num_vcpus: 12  cvm_uuid:
  "d39c8813-9029-4228-ad5e-d1e82fc82e0f"  logical_timestamp:'
