dependencies:
- related
knowledge_base:
  extraction_date: '2025-01-28'
  source_file: /home/sravya.venkamsetty/NLP-Based-KBA-Hackathon-/data/raw/KB-1.pdf
validations:
- issue
- failure
- error
- exception
